//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LabelResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UsExpress.Transport.Web.FrontEnd.App_GlobalResources.Language", typeof(Language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Name Required.
        /// </summary>
        public static string lb_AccountNameRequired {
            get {
                return ResourceManager.GetString("lb_AccountNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action had error, please try again!.
        /// </summary>
        public static string lb_actionError {
            get {
                return ResourceManager.GetString("lb_actionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add items to Package.
        /// </summary>
        public static string lb_AdditemstoPackage {
            get {
                return ResourceManager.GetString("lb_AdditemstoPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barcode Required.
        /// </summary>
        public static string lb_BarcodeRequired {
            get {
                return ResourceManager.GetString("lb_BarcodeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category Required.
        /// </summary>
        public static string lb_CategoryRequired {
            get {
                return ResourceManager.GetString("lb_CategoryRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Category.
        /// </summary>
        public static string lb_ChooseCategory {
            get {
                return ResourceManager.GetString("lb_ChooseCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New Receiver Succeed.
        /// </summary>
        public static string lb_CreateNewRecieverSucceed {
            get {
                return ResourceManager.GetString("lb_CreateNewRecieverSucceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New Sender Succeed.
        /// </summary>
        public static string lb_CreateNewSenderSucceed {
            get {
                return ResourceManager.GetString("lb_CreateNewSenderSucceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New Store Succeed.
        /// </summary>
        public static string lb_CreateNewStoreSucceed {
            get {
                return ResourceManager.GetString("lb_CreateNewStoreSucceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New User Succeed.
        /// </summary>
        public static string lb_CreateNewUserSucceed {
            get {
                return ResourceManager.GetString("lb_CreateNewUserSucceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New Warehouse Succeed.
        /// </summary>
        public static string lb_CreateNewWarehouseSucceed {
            get {
                return ResourceManager.GetString("lb_CreateNewWarehouseSucceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new product success!.
        /// </summary>
        public static string lb_CreateProductSuccess {
            get {
                return ResourceManager.GetString("lb_CreateProductSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Shipment Failed.
        /// </summary>
        public static string lb_CreateShipmentError {
            get {
                return ResourceManager.GetString("lb_CreateShipmentError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Store Succeed).
        /// </summary>
        public static string lb_CreateStoreSecceed {
            get {
                return ResourceManager.GetString("lb_CreateStoreSecceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description Required.
        /// </summary>
        public static string lb_DescriptionRequired {
            get {
                return ResourceManager.GetString("lb_DescriptionRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You dont have store info!.
        /// </summary>
        public static string lb_DontHaveStoreInfo {
            get {
                return ResourceManager.GetString("lb_DontHaveStoreInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string lb_Error {
            get {
                return ResourceManager.GetString("lb_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Account has not Activated, Please Contact Administrator.
        /// </summary>
        public static string lb_errorAccount {
            get {
                return ResourceManager.GetString("lb_errorAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action had error or barcode is exists, please try again!.
        /// </summary>
        public static string lb_errorActionAndBarCode {
            get {
                return ResourceManager.GetString("lb_errorActionAndBarCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed.
        /// </summary>
        public static string lb_Failed {
            get {
                return ResourceManager.GetString("lb_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has error, please try again!.
        /// </summary>
        public static string lb_HasError {
            get {
                return ResourceManager.GetString("lb_HasError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Info, Reenter.
        /// </summary>
        public static string lb_InvalidInfoReenter {
            get {
                return ResourceManager.GetString("lb_InvalidInfoReenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Account Can&apos;t Create A New Order.
        /// </summary>
        public static string lb_NotPermissionOrder {
            get {
                return ResourceManager.GetString("lb_NotPermissionOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Created Succesful.
        /// </summary>
        public static string lb_OrderCreatedSuccesful {
            get {
                return ResourceManager.GetString("lb_OrderCreatedSuccesful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Updated Succesful.
        /// </summary>
        public static string lb_OrderUpdatedSuccesful {
            get {
                return ResourceManager.GetString("lb_OrderUpdatedSuccesful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Packager&apos;s Info Required.
        /// </summary>
        public static string lb_PackageInfoRequired {
            get {
                return ResourceManager.GetString("lb_PackageInfoRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package Required.
        /// </summary>
        public static string lb_PackageRequired {
            get {
                return ResourceManager.GetString("lb_PackageRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package&apos;s Info Required.
        /// </summary>
        public static string lb_PackagesInfoRequired {
            get {
                return ResourceManager.GetString("lb_PackagesInfoRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Required.
        /// </summary>
        public static string lb_PasswordRequired {
            get {
                return ResourceManager.GetString("lb_PasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number&apos;s Already Existed.
        /// </summary>
        public static string lb_PhoneNumbersAlreadyExisted {
            get {
                return ResourceManager.GetString("lb_PhoneNumbersAlreadyExisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Choose A Package To Print.
        /// </summary>
        public static string lb_PleaseChooseAPackageToPrint {
            get {
                return ResourceManager.GetString("lb_PleaseChooseAPackageToPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipient&apos;s Require.
        /// </summary>
        public static string lb_RecipientsRequire {
            get {
                return ResourceManager.GetString("lb_RecipientsRequire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register Failed.
        /// </summary>
        public static string lb_RegisterFailed {
            get {
                return ResourceManager.GetString("lb_RegisterFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register Succeed.
        /// </summary>
        public static string lb_RegisterSucceed {
            get {
                return ResourceManager.GetString("lb_RegisterSucceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required.
        /// </summary>
        public static string lb_Required {
            get {
                return ResourceManager.GetString("lb_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sender&apos;s Info Required.
        /// </summary>
        public static string lb_SendersInfoRequired {
            get {
                return ResourceManager.GetString("lb_SendersInfoRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipment Required.
        /// </summary>
        public static string lb_ShipmentRequired {
            get {
                return ResourceManager.GetString("lb_ShipmentRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Succeed.
        /// </summary>
        public static string lb_Succeed {
            get {
                return ResourceManager.GetString("lb_Succeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Failed.
        /// </summary>
        public static string lb_UpdateFailed {
            get {
                return ResourceManager.GetString("lb_UpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Info dont success.
        /// </summary>
        public static string lb_UpdateInfodontsuccess {
            get {
                return ResourceManager.GetString("lb_UpdateInfodontsuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update info Failed.
        /// </summary>
        public static string lb_UpdateinfoFailed {
            get {
                return ResourceManager.GetString("lb_UpdateinfoFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update info success.
        /// </summary>
        public static string lb_Updateinfosuccess {
            get {
                return ResourceManager.GetString("lb_Updateinfosuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Password Failed.
        /// </summary>
        public static string lb_UpdatePasswordFailed {
            get {
                return ResourceManager.GetString("lb_UpdatePasswordFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Password Succeed.
        /// </summary>
        public static string lb_UpdatePasswordSucceed {
            get {
                return ResourceManager.GetString("lb_UpdatePasswordSucceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update product success!.
        /// </summary>
        public static string lb_UpdateProductSuccess {
            get {
                return ResourceManager.GetString("lb_UpdateProductSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Receiver Succeed.
        /// </summary>
        public static string lb_UpdateRecieverSucceed {
            get {
                return ResourceManager.GetString("lb_UpdateRecieverSucceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Role Succeed.
        /// </summary>
        public static string lb_UpdateRoleSucceed {
            get {
                return ResourceManager.GetString("lb_UpdateRoleSucceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Sender Succeed.
        /// </summary>
        public static string lb_UpdateSenderSucceed {
            get {
                return ResourceManager.GetString("lb_UpdateSenderSucceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Store Succeed.
        /// </summary>
        public static string lb_UpdateStoreSucceed {
            get {
                return ResourceManager.GetString("lb_UpdateStoreSucceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Succeed.
        /// </summary>
        public static string lb_UpdateSucceed {
            get {
                return ResourceManager.GetString("lb_UpdateSucceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Successful.
        /// </summary>
        public static string lb_UpdateSuccessful {
            get {
                return ResourceManager.GetString("lb_UpdateSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update User Succeed.
        /// </summary>
        public static string lb_UpdateUserSucceed {
            get {
                return ResourceManager.GetString("lb_UpdateUserSucceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Warehouse Succeed.
        /// </summary>
        public static string lb_UpdateWarehouseSucceed {
            get {
                return ResourceManager.GetString("lb_UpdateWarehouseSucceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username Required.
        /// </summary>
        public static string lb_UsernameRequired {
            get {
                return ResourceManager.GetString("lb_UsernameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong Password.
        /// </summary>
        public static string lb_WrongPassword {
            get {
                return ResourceManager.GetString("lb_WrongPassword", resourceCulture);
            }
        }
    }
}
