//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UsExpress.Transport.Lib.Business.Models.DBContext.UsTransport
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblItemInPackage
    {
        public int id { get; set; }
        public Nullable<int> PackageId { get; set; }
        public string Description { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public string Code { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<decimal> Value { get; set; }
        public string Unit { get; set; }
        public string BarCode { get; set; }
    
        public virtual tblCategory tblCategory { get; set; }
        public virtual tblPackageInfo tblPackageInfo { get; set; }
    }
}
