//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UsExpress.Transport.Lib.Business.Models.DBContext.UsTransport
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblKerryPostNewOrder
    {
        public int Id { get; set; }
        public Nullable<long> OrderId { get; set; }
        public string Status { get; set; }
        public string Message { get; set; }
        public string OrderNumber { get; set; }
        public string Cost { get; set; }
        public string WoodBaleFee { get; set; }
        public string RemoteDeliverFee { get; set; }
        public string DeliveryDate { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
