//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UsExpress.Transport.Lib.Business.Models.DBContext.UsTransport
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblOrder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblOrder()
        {
            this.tblPackageInfoes = new HashSet<tblPackageInfo>();
        }
    
        public long id { get; set; }
        public string Code { get; set; }
        public Nullable<int> SenderId { get; set; }
        public Nullable<int> RecipientId { get; set; }
        public Nullable<int> TotalPackage { get; set; }
        public Nullable<decimal> Weight { get; set; }
        public Nullable<decimal> TotalCharge { get; set; }
        public Nullable<int> Exedite { get; set; }
        public long CreateDate { get; set; }
        public Nullable<long> PickupDate { get; set; }
        public Nullable<long> ShippingDate { get; set; }
        public Nullable<long> ClearCustomDate { get; set; }
        public Nullable<long> Deliver { get; set; }
        public Nullable<int> Status { get; set; }
        public string Tracking { get; set; }
        public Nullable<int> Destination { get; set; }
        public string Note { get; set; }
        public Nullable<int> StoreId { get; set; }
        public Nullable<int> NotifyToCustomer { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string BarCode { get; set; }
        public bool IsActive { get; set; }
        public Nullable<long> TotalItems { get; set; }
        public Nullable<decimal> TotalDeclareValues { get; set; }
        public Nullable<decimal> ShippingFree { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPackageInfo> tblPackageInfoes { get; set; }
    }
}
