//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UsExpress.Transport.Lib.Business.Models.DBContext.UsTransport
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblStateProvice
    {
        public string Id { get; set; }
        public int CountryId { get; set; }
        public string Name { get; set; }
        public string ShortName { get; set; }
        public Nullable<bool> Published { get; set; }
        public Nullable<int> DisplayOrder { get; set; }
        public Nullable<int> AirPort { get; set; }
    
        public virtual tblCountry tblCountry { get; set; }
    }
}
