//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UsExpress.Transport.Lib.Business.Models.DBContext.UsTransport
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class UsTransportEntities : DbContext
    {
    	public UsTransportEntities(string connectionString)
            : base(connectionString)
        {}
    
        public UsTransportEntities()
            : base("name=UsTransportEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Test> Tests { get; set; }
        public virtual DbSet<tblMenu> tblMenus { get; set; }
        public virtual DbSet<tblMenuPermission> tblMenuPermissions { get; set; }
        public virtual DbSet<tblRole> tblRoles { get; set; }
        public virtual DbSet<tblUserRole> tblUserRoles { get; set; }
        public virtual DbSet<tblCity> tblCities { get; set; }
        public virtual DbSet<tblDistrict> tblDistricts { get; set; }
        public virtual DbSet<tblState> tblStates { get; set; }
        public virtual DbSet<tblCategory> tblCategories { get; set; }
        public virtual DbSet<tblCountry> tblCountries { get; set; }
        public virtual DbSet<tblItemInPackage> tblItemInPackages { get; set; }
        public virtual DbSet<tblKerryPostNewOrder> tblKerryPostNewOrders { get; set; }
        public virtual DbSet<tblKerryStatusService> tblKerryStatusServices { get; set; }
        public virtual DbSet<tblDistrictStateProvice> tblDistrictStateProvices { get; set; }
        public virtual DbSet<tblStateProvice> tblStateProvices { get; set; }
        public virtual DbSet<tblWard> tblWards { get; set; }
        public virtual DbSet<tblShippingInfo> tblShippingInfoes { get; set; }
        public virtual DbSet<tblRecipientsInfo> tblRecipientsInfoes { get; set; }
        public virtual DbSet<tblSender> tblSenders { get; set; }
        public virtual DbSet<tblKerryOrderProgress> tblKerryOrderProgresses { get; set; }
        public virtual DbSet<tblOrder> tblOrders { get; set; }
        public virtual DbSet<tblTypeCategory> tblTypeCategories { get; set; }
        public virtual DbSet<tblTypeAcount> tblTypeAcounts { get; set; }
        public virtual DbSet<tblWarehouse> tblWarehouses { get; set; }
        public virtual DbSet<tblStoreAccount> tblStoreAccounts { get; set; }
        public virtual DbSet<tblUser> tblUsers { get; set; }
        public virtual DbSet<tblShipment> tblShipments { get; set; }
        public virtual DbSet<tblAppUserRoleMenu> tblAppUserRoleMenus { get; set; }
        public virtual DbSet<tblPackageInfo> tblPackageInfoes { get; set; }
        public virtual DbSet<tblProduct> tblProducts { get; set; }
        public virtual DbSet<EmailTemplate> EmailTemplates { get; set; }
        public virtual DbSet<tblStatusOrder> tblStatusOrders { get; set; }
        public virtual DbSet<Log> Logs { get; set; }
    }
}
